const voterKey = 'vota-voter-id-v1';
const voterId = localStorage.getItem(voterKey) || (() => { const id = crypto.randomUUID(); localStorage.setItem(voterKey, id); return id; })();
const $ = id => document.getElementById(id);
let state = { active: null, history: [] }, managerPin = '';
const api = async (url, options = {}) => { const r = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(managerPin ? { 'x-manager-pin': managerPin } : {}), ...options.headers }, ...options }); const result = await r.json(); if (!r.ok) throw new Error(result.error || 'Não foi possível concluir o pedido.'); return result; };
const timeLeft = () => state.active ? Math.max(0, Math.ceil((state.active.endsAt - Date.now()) / 1000)) : 0;
const clock = seconds => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;
const stats = (item = state.active) => item?.metrics || (() => { const all = Object.values(item?.votes || {}), yes = all.filter(v => v === 'yes').length; return { total: all.length, yes, percent: all.length ? Math.round(yes / all.length * 100) : 0 }; })();
const safe = value => { const d = document.createElement('div'); d.textContent = value; return d.innerHTML; };
function history() { const records = state.history || []; $('historyCount').textContent = `${records.length} registo${records.length === 1 ? '' : 's'}`; $('historyList').innerHTML = records.length ? records.map(item => { const s = stats(item), date = new Date(item.endedAt).toLocaleString('pt-PT', { dateStyle: 'medium', timeStyle: 'short' }); return `<article class="history-item"><div><strong>${safe(item.subject)} passa?</strong><small class="date">Encerrada em ${date}</small></div><div><strong class="rate">${s.percent}%</strong><small>aceitação</small></div><div><strong>${s.yes}</strong><small>votos “Sim” · ${s.total} total</small></div></article>`; }).join('') : '<p class="empty-history">Ainda não há votações concluídas.</p>'; }
function render() { const open = state.active && timeLeft() > 0, mine = state.active?.myVote || state.active?.votes?.[voterId], s = stats(); $('voteQuestion').textContent = state.active ? `${state.active.subject} passa?` : 'Aguardando a próxima votação'; $('statusText').textContent = open ? 'VOTAÇÃO EM CURSO' : 'SEM VOTAÇÃO ATIVA'; $('timer').textContent = open ? clock(timeLeft()) : '—'; $('voteHelper').textContent = open ? 'Escolha a sua resposta. Pode mudar o voto enquanto o tempo estiver a decorrer.' : 'O gestor ainda não iniciou uma votação.'; document.querySelectorAll('.choice').forEach(b => { b.disabled = !open; b.classList.toggle('selected', b.dataset.vote === mine); }); $('voteNote').textContent = mine && open ? `Voto registado: “${mine === 'yes' ? 'Sim' : 'Não'}”. Pode alterá-lo até ao fim.` : open ? 'O seu voto é privado e pode ser alterado durante a votação.' : 'O seu voto é privado.'; $('activeTitle').textContent = state.active ? `${state.active.subject} passa?` : 'Sem votação ativa'; $('yesPercent').textContent = state.active ? `${s.percent}%` : '—'; $('yesCount').textContent = s.yes; $('totalCount').textContent = s.total; $('approvalBar').style.width = `${s.percent}%`; $('activeTimer').textContent = open ? `Termina em ${clock(timeLeft())}` : '—'; $('endVote').disabled = !state.active; history(); }
async function refresh() { try { state = await api(`/api/state?voterId=${encodeURIComponent(voterId)}`); render(); } catch { $('voteHelper').textContent = 'Não foi possível ligar ao serviço de votação.'; } }
async function managerRefresh() { state = await api('/api/manage/state'); render(); }
document.querySelectorAll('.choice').forEach(b => b.addEventListener('click', async () => { try { state = await api('/api/vote', { method: 'POST', body: JSON.stringify({ voterId, choice: b.dataset.vote }) }); if (navigator.vibrate) navigator.vibrate(18); render(); } catch (e) { $('voteNote').textContent = e.message; } }));
$('openManager').addEventListener('click', () => { $('pinError').classList.add('hidden'); $('pin').value = ''; $('pinDialog').showModal(); setTimeout(() => $('pin').focus(), 100); }); $('cancelPin').addEventListener('click', () => $('pinDialog').close());
$('pinForm').addEventListener('submit', async e => { e.preventDefault(); managerPin = $('pin').value; try { await api('/api/manage/verify', { method: 'POST' }); $('pinDialog').close(); $('voteView').classList.add('hidden'); $('managerView').classList.remove('hidden'); managerRefresh(); } catch { managerPin = ''; $('pinError').classList.remove('hidden'); if (navigator.vibrate) navigator.vibrate([30, 35, 30]); } });
$('closeManager').addEventListener('click', () => { $('managerView').classList.add('hidden'); $('voteView').classList.remove('hidden'); });
$('newVoteForm').addEventListener('submit', async e => { e.preventDefault(); try { state = await api('/api/manage/start', { method: 'POST', body: JSON.stringify({ subject: $('subject').value, minutes: Number($('duration').value) }) }); $('subject').value = ''; render(); } catch (error) { alert(error.message); } }); $('endVote').addEventListener('click', async () => { try { state = await api('/api/manage/end', { method: 'POST' }); render(); } catch (error) { alert(error.message); } });
new EventSource('/api/events').onmessage = event => { state = JSON.parse(event.data); managerPin && !$('managerView').classList.contains('hidden') ? managerRefresh() : render(); }; refresh(); setInterval(render, 1000);
